spring.application.name=12_ONG_ENDY_PVH_SPRING_Homework002
server.port =  9090
spring.datasource.url = jdbc:postgresql://localhost:5432/mybatis_db
spring.datasource.username = postgres
spring.datasource.password = endy123$$&&
spring.datasource.driver-class-name=org.postgresql.Driver